services:

  ###############################################################################
  # MOSQUITTO (ARM64 OK)
  ###############################################################################
  mosquitto:
    image: eclipse-mosquitto:1.6
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883" 
      - "8883:8883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  ###############################################################################
  # INFLUXDB (ARM64 OK)
  ###############################################################################
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
    environment:
      INFLUXDB_DB: telemetry
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER:-admin}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD:-admin}
      INFLUXDB_USER: ${INFLUXDB_USER:-telegraf}
      INFLUXDB_USER_PASSWORD: ${INFLUXDB_PASSWORD:-metricsmetricsmetrics}    
    ports:
      - "8086:8086"
    volumes:
   #   - ./influxdb:/var/lib/influxdb
      - ${INFLUX_DB_DATA}:/var/lib/influxdb
  ###############################################################################
  # TELEGRAF (ARM64 OK)
  ###############################################################################
  telegraf:
    image: telegraf:1.30
    container_name: telegraf
    restart: unless-stopped
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      MOSQUITTO_USERNAME: ${MOSQUITTO_USERNAME}
      MOSQUITTO_PASSWORD: ${MOSQUITTO_PASSWORD}
    depends_on:
      - mosquitto
      - influxdb

  ###############################################################################
  # GRAFANA (ARM64 OK)
  ###############################################################################
  grafana:
    image: grafana/grafana:10.4.3
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"  
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "false"    
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning

  
